### ISSUE TITLE
False Positive Case

### ISSUE THREAD

**Issue by cupcake-shukla** [securing/IOSSecuritySuite#25]
Hi, One of our customers devices is returning the message that it is jailbroken but according to him the device is not jailbroken

I have checked his device with one other library DVIA and it is showing that the device is not jailbroken

**Comment by vocaeq** [comment]
Hello @cupcake-shukla,
Thanks for contacting us. Could you provide us some more information, like which device was used and it's iOS version? Also, was that device jailbroken before?

**Comment by cupcake-shukla** [comment]
Device model name - iPhone 7 Plus
Device model number - NN5T2LL/A
Device manufacturer - Apple
OS version - 13.6

It was not jailbroken before

**Comment by vocaeq** [comment]
Could you also provide us message returned by IOSSecuritySuite.amIJailbrokenWithFailMessage()
Here's code snipped:
```
let jailbreakStatus = IOSSecuritySuite.amIJailbrokenWithFailMessage()
if jailbreakStatus.jailbroken {
	print("This device is jailbroken")
	print("Because: \(jailbreakStatus.failMessage)")
} else {
	print("This device is not jailbroken")
}
```

**Comment by r3ggi** [comment]
I've just used the ISS on jailed iPhone XS with iOS 13.6. It works as expected.

Are you sure that the client uses the newest ISS? We have fixed one false positive in https://github.com/securing/IOSSecuritySuite/commit/5abdf9c2e6203b088a4b9fc3e69a7bf6a2eb0231

**Comment by cupcake-shukla** [comment]
Yes after the issue was reported  I had updated the library to 1.6.0 version which is the latest one but still the issue persists , i have asked him to share the fail message will update here as soon as possible.

**Comment by cupcake-shukla** [comment]
Hi, PFA the screenshot shared by the user it shows that Suspicious file exists at  - /var/log/apt
![JAILBRK](https://user-images.githubusercontent.com/19852983/92076402-1b012480-edd8-11ea-889e-01b7d4301c20.jpg)

**Comment by r3ggi** [comment]
Hey @cupcake-shukla,

The detected directory is `/var/log/apt` what contains logs created by apt, the packet manager. It is used by Cydia/Sileo what means that the iPhone is jailbroken or was jailbroken in the past. As the applications are sandboxed they cannot write to the `/var/log`.
If users want to get rid of such files they have to restore the rootfs instead of wiping iOS.

**Comment by cupcake-shukla** [comment]
Hi @r3ggi  can you please share some more details on this part how can we do it - "If users want to get rid of such files they have to restore the rootfs instead of wiping their devices (from system settings).

"

**Comment by vocaeq** [comment]
Hello @cupcake-shukla,

First of all client seems to be on version that is supported by current jailbreaks. Before going any further, please perform backup of device in iTunes. To solve a problem client can use [checkra1n](https://checkra.in) to get into jailbroken state, open installed checkra1n app on phone and choose "restore system" option.  If problem persists, it is recommended to perform full iOS restore from iTunes application. [Apple guide for system restore might](https://support.apple.com/en-us/HT201252) come useful here.

Secondly, we recommend, if not necessary, not to kill your app when the jailbroken state is detected. Instead, it's a good practice to inform users about the danger that comes from having such modification and give a choice to continue using the application. However, if for a business reason, having functionality that kills application is required, you can always filter "/var/log/apt" and ignore it instead of killing application, which may stop previously jailbroken devices from being detected.

**Comment by cupcake-shukla** [comment]
Thank you for all the help. Really Appreciate it.

**Comment by r3ggi** [comment]
You're welcome! If you do not any further questions, feel free to close this issue.

**Comment by giofid** [comment]
Hi @vocaeq,
I'm using ISS in my app, so I'm interested in this discussion. I have a question. Ignoring the "/var/log/apt" folder existence could stop also  **currently** jailbroken devices from being detected?

**Comment by r3ggi** [comment]
Hey @giofid 

Currently jailbroken devices have the `/var/log/apt` directory created, so ignoring it decreases the ISS' effectiveness. However, the ISS checks more jb indicators, so in most cases it will work correctly.

**Comment by r3ggi** [comment]
+ Please keep in mind that the ISS will return that false positive only when user unjailbroke their device incorrectly.

**Comment by giofid** [comment]
Hi @r3ggi,
thank you for your reply. 

I asked because in a currently jailbroken device, I don't find a case where all ISS checks pass except` /var/log/apt` existence. So I've been thinking this check could be safely removed.

**Comment by r3ggi** [comment]
That's true, however we want to keep all possible files/directories created by jailbreak services. The reason is to defeat jailbreak detectors. The more files/directories we look for, the harder is to bypass the ISS.
