### ISSUE TITLE
denySymbolHook crash on iOS 14

### ISSUE THREAD

**Issue by Anthony-GitHub** [securing/IOSSecuritySuite#33]
denySymbolHook works when the app is running by XCode. The app crashed when I launch it directly without XCode. This happened on iOS 14. I can run the same app on iOS 12 without any issue.

The FrameworkClientDemo can reproduce this by adding code in viewDidAppear:
```
      IOSSecuritySuite.denySymbolHook("dlopen")
      let kernelHandle = dlopen("/usr/lib/system/libsystem_kernel.dylib", RTLD_LAZY)
```

The crash is not in the denySymbolHook method. When the symbol is invoked after denySymbolHook, then it crashes.
If I remove the first line code, then the app will not crash.

The crash log:

```
Hardware Model:      iPhone10,3
Process:             FrameworkClientApp [864]
Path:                /private/var/containers/Bundle/Application/0D0EA6FE-4CF8-42BC-8C4E-2289508F61A1/FrameworkClientApp.app/FrameworkClientApp
Identifier:          biz.securing.FrameworkClientApp.test20201120
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           biz.securing.FrameworkClientApp.test20201120 [780]


Date/Time:           2020-11-20 14:19:52.5214 +0800
Launch Time:         2020-11-20 14:19:52.3926 +0800
OS Version:          iPhone OS 14.2 (18B92)
Release Type:        User
Baseband Version:    6.02.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4310532096
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   100ed8000-100eec000 [   80K] r-x/r-x SM=COW  ...workClientApp

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [864]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   ???                             000000000000000000 0 + 0
1   libdyld.dylib                   0x0000000192f57fc0 dyld_stub_binder + 60
2   FrameworkClientApp              0x0000000100ee55cc 0x100ed8000 + 54732
3   FrameworkClientApp              0x0000000100ee6e9c 0x100ed8000 + 61084
4   UIKitCore                       0x00000001954a4e20 -[UIViewController _setViewAppearState:isAnimating:] + 832
5   UIKitCore                       0x00000001954a5780 -[UIViewController __viewDidAppear:] + 168
6   UIKitCore                       0x00000001954a5a80 -[UIViewController _endAppearanceTransition:] + 248
7   UIKitCore                       0x000000019538eb30 __48-[UIPresentationController transitionDidFinish:]_block_invoke + 136
8   UIKitCore                       0x000000019600ae40 -[_UIAfterCACommitBlock run] + 64
9   UIKitCore                       0x0000000195b6fcc8 _runAfterCACommitDeferredBlocks + 296
10  UIKitCore                       0x0000000195b5f1f8 _cleanUpAfterCAFlushAndRunDeferredBlocks + 200
11  UIKitCore                       0x0000000195b90790 _afterCACommitHandler + 76
12  CoreFoundation                  0x000000019327c86c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
13  CoreFoundation                  0x0000000193276f40 __CFRunLoopDoObservers + 604
14  CoreFoundation                  0x0000000193277488 __CFRunLoopRun + 960
15  CoreFoundation                  0x0000000193276b90 CFRunLoopRunSpecific + 572
16  GraphicsServices                0x00000001a9599598 GSEventRunModal + 160
17  UIKitCore                       0x0000000195b60638 -[UIApplication _run] + 1052
18  UIKitCore                       0x0000000195b65bb8 UIApplicationMain + 164
19  FrameworkClientApp              0x0000000100ee7964 0x100ed8000 + 63844
20  libdyld.dylib                   0x0000000192f55588 start + 4

Thread 1:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 6 name:  com.apple.uikit.eventfetch-thread
Thread 6:
0   libsystem_kernel.dylib          0x00000001be3a2644 mach_msg_trap + 8
1   libsystem_kernel.dylib          0x00000001be3a1a48 mach_msg + 72
2   CoreFoundation                  0x000000019327d0ec __CFRunLoopServiceMachPort + 376
3   CoreFoundation                  0x0000000193277560 __CFRunLoopRun + 1176
4   CoreFoundation                  0x0000000193276b90 CFRunLoopRunSpecific + 572
5   Foundation                      0x00000001944947f8 -[NSRunLoop+ 30712 (NSRunLoop) runMode:beforeDate:] + 228
6   Foundation                      0x00000001944946d8 -[NSRunLoop+ 30424 (NSRunLoop) runUntilDate:] + 88
7   UIKitCore                       0x0000000195c0c438 -[UIEventFetcher threadMain] + 504
8   Foundation                      0x00000001945f14bc __NSThread__start__ + 848
9   libsystem_pthread.dylib         0x00000001d9908b3c _pthread_start + 288
10  libsystem_pthread.dylib         0x00000001d990d880 thread_start + 8

Thread 7:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib         0x00000001d990d86c start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000192f84714   x1: 0x00000001e9adb0e0   x2: 0x0000000000000000   x3: 0x00000001e9b158c0
    x4: 0x00000001e9b15910   x5: 0x0000000000000008   x6: 0x00000001e9b15918   x7: 0x00000001ea238710
    x8: 0x00000001e9ada000   x9: 0x0000000000000001  x10: 0xfffffffe00000000  x11: 0x0000000000000000
   x12: 0x0000000000000003  x13: 0x00000001970566a0  x14: 0x0000000000020000  x15: 0x0000000000000002
   x16: 0x0000000192f57f84  x17: 0x0000000100eed8b8  x18: 0x0000000000000000  x19: 0x0000000000000dc4
   x20: 0x0000000100eed8b8  x21: 0x00000001e9adb0e0  x22: 0x0000000106205860  x23: 0x0000000000000001
   x24: 0x0000000000000000  x25: 0x00000001dba1f000  x26: 0x0000000000000001  x27: 0x00000001dc06f000
   x28: 0x00000001ea191000   fp: 0x000000016ef25d90   lr: 0x0000000192f598bc
    sp: 0x000000016ef25d70   pc: 0x0000000000000000 cpsr: 0x60000000
   esr: 0x82000006 (Instruction Abort) Translation fault

```

**Comment by TannerJin** [comment]
@Anthony-GitHub hi, this issue has been fixed

**Comment by Anthony-GitHub** [comment]
@TannerJin Thanks. 

The app still crashes if I rebind the symbol by fishhook before calling `IOSSecuritySuite.denySymbolHook("dlopen")`. The crash log is the same as above.
```
  struct rebinding rebindDlopen;
  rebindDlopen.name = "dlopen";
  rebindDlopen.replacement = mydlopen;
  rebindDlopen.replaced = (void *)&sys_dlopen;
  
  struct rebinding rebs[1] = {rebindDlopen};
  rebind_symbols(rebs, 1);

```

**Comment by TannerJin** [comment]
yep, you hook the `dlopen` method and system dylib maybe use `dlopen` method during running .

``` swift
typealias MyDlopen = @convention(thin) (UnsafePointer<Int8>?, Int32) -> UnsafeMutableRawPointer?

func myDlopen(_ __path: UnsafePointer<Int8>!, _ __mode: Int32) -> UnsafeMutableRawPointer! {
     print("myDlopen")
     return nil
}
        
let new: MyDlopen = myDlopen
var old: UnsafeMutableRawPointer?

replaceSymbol("dlopen", image: _dyld_get_image_header(0), imageSlide: _dyld_get_image_vmaddr_slide(0), newMethod: unsafeBitCast(new, to: UnsafeMutableRawPointer.self), oldMethod: &old)
```

you can just hook the main executable file and will not affect others system library.

**Comment by Anthony-GitHub** [comment]
@TannerJin The problem is that if 'dlopen' method is hooked, then the app will crash. This is due to 'IOSSecuritySuite.denySymbolHook("dlopen")' try to rebind the symbol. It seems to rebind the 'dlopen' to an invalid address.

Is there a way we can avoid the crash when 'dlopen' method is hooked?

After some tests, I found it crash on iOS 13 and iOS 14. The iOS 12 works. So this may be related to the dyld 3? The major change for dyld 3 is that they will be doing full symbol resolution at launch time, rather than using the on-demand resolution using trampolines.
https://developer.apple.com/videos/play/wwdc2017/413/

**Comment by TannerJin** [comment]
actually，on iOS 13 and iOS iOS14, `IOSSecuritySuite.denySymbolHook("dlopen")` doesn't work for system librarys, because the system librarys's `stub_helper` section has been change to `auth_stubs` section. the method just works on yourself dylib.

you can test by hook `print` or `NSLog` method or just hook `dlopen` at yourself dylib. And not affect the runing of system librarys.

**Comment by r3ggi** [comment]
Hey @TannerJin and @Anthony-GitHub,

As the `IOSSecuritySuite.denySymbolHook()` is unable to hook symbols from system libraries, maybe we should update the documentation?
